# Generated by Django 5.2.7 on 2025-10-28 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
