# Generated by Django 5.2.7 on 2025-10-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda']},
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
